#!/bin/bash

awk '
/Started/ {
    for (i=0; i<=NF; i++) {
        if ($i ~ /^(GET|POST|PATCH|DELETE|PUT)$/) {
            request = $i " " $(i+1)
            break
        }
    }
    next
}
/Completed/ {
    for(i=0; i<=NF; i++) 
        if($i=="in" && $(i+1)~/[0-9]+ms/) {
            time = $(i+1)
            print time, request
            next
        }
}' "$1" | sort -rn | head -1

